# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import kv_pb2 as kv__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in kv_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class KVServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Put = channel.unary_unary(
                '/kv.KVService/Put',
                request_serializer=kv__pb2.PutRequest.SerializeToString,
                response_deserializer=kv__pb2.Reply.FromString,
                _registered_method=True)
        self.Get = channel.unary_unary(
                '/kv.KVService/Get',
                request_serializer=kv__pb2.KeyRequest.SerializeToString,
                response_deserializer=kv__pb2.ValueReply.FromString,
                _registered_method=True)
        self.Delete = channel.unary_unary(
                '/kv.KVService/Delete',
                request_serializer=kv__pb2.KeyRequest.SerializeToString,
                response_deserializer=kv__pb2.Reply.FromString,
                _registered_method=True)
        self.ReplicaPut = channel.unary_unary(
                '/kv.KVService/ReplicaPut',
                request_serializer=kv__pb2.PutRequest.SerializeToString,
                response_deserializer=kv__pb2.Reply.FromString,
                _registered_method=True)
        self.ReplicaDelete = channel.unary_unary(
                '/kv.KVService/ReplicaDelete',
                request_serializer=kv__pb2.KeyRequest.SerializeToString,
                response_deserializer=kv__pb2.Reply.FromString,
                _registered_method=True)
        self.Ping = channel.unary_unary(
                '/kv.KVService/Ping',
                request_serializer=kv__pb2.Empty.SerializeToString,
                response_deserializer=kv__pb2.Reply.FromString,
                _registered_method=True)
        self.Recover = channel.unary_unary(
                '/kv.KVService/Recover',
                request_serializer=kv__pb2.PartitionRequest.SerializeToString,
                response_deserializer=kv__pb2.DataDump.FromString,
                _registered_method=True)


class KVServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Put(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReplicaPut(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReplicaDelete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Recover(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KVServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Put': grpc.unary_unary_rpc_method_handler(
                    servicer.Put,
                    request_deserializer=kv__pb2.PutRequest.FromString,
                    response_serializer=kv__pb2.Reply.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=kv__pb2.KeyRequest.FromString,
                    response_serializer=kv__pb2.ValueReply.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=kv__pb2.KeyRequest.FromString,
                    response_serializer=kv__pb2.Reply.SerializeToString,
            ),
            'ReplicaPut': grpc.unary_unary_rpc_method_handler(
                    servicer.ReplicaPut,
                    request_deserializer=kv__pb2.PutRequest.FromString,
                    response_serializer=kv__pb2.Reply.SerializeToString,
            ),
            'ReplicaDelete': grpc.unary_unary_rpc_method_handler(
                    servicer.ReplicaDelete,
                    request_deserializer=kv__pb2.KeyRequest.FromString,
                    response_serializer=kv__pb2.Reply.SerializeToString,
            ),
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=kv__pb2.Empty.FromString,
                    response_serializer=kv__pb2.Reply.SerializeToString,
            ),
            'Recover': grpc.unary_unary_rpc_method_handler(
                    servicer.Recover,
                    request_deserializer=kv__pb2.PartitionRequest.FromString,
                    response_serializer=kv__pb2.DataDump.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kv.KVService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kv.KVService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class KVService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Put(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kv.KVService/Put',
            kv__pb2.PutRequest.SerializeToString,
            kv__pb2.Reply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kv.KVService/Get',
            kv__pb2.KeyRequest.SerializeToString,
            kv__pb2.ValueReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kv.KVService/Delete',
            kv__pb2.KeyRequest.SerializeToString,
            kv__pb2.Reply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReplicaPut(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kv.KVService/ReplicaPut',
            kv__pb2.PutRequest.SerializeToString,
            kv__pb2.Reply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReplicaDelete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kv.KVService/ReplicaDelete',
            kv__pb2.KeyRequest.SerializeToString,
            kv__pb2.Reply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kv.KVService/Ping',
            kv__pb2.Empty.SerializeToString,
            kv__pb2.Reply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Recover(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kv.KVService/Recover',
            kv__pb2.PartitionRequest.SerializeToString,
            kv__pb2.DataDump.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
