# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kv.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'kv.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08kv.proto\x12\x02kv\"(\n\nPutRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"\x19\n\nKeyRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\")\n\x05Reply\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"*\n\nValueReply\x12\r\n\x05\x66ound\x18\x01 \x01(\x08\x12\r\n\x05value\x18\x02 \x01(\t\"\x07\n\x05\x45mpty\"(\n\x10PartitionRequest\x12\x14\n\x0cpartition_id\x18\x01 \x01(\x05\"]\n\x08\x44\x61taDump\x12$\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x16.kv.DataDump.DataEntry\x1a+\n\tDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32\x9b\x02\n\tKVService\x12 \n\x03Put\x12\x0e.kv.PutRequest\x1a\t.kv.Reply\x12%\n\x03Get\x12\x0e.kv.KeyRequest\x1a\x0e.kv.ValueReply\x12#\n\x06\x44\x65lete\x12\x0e.kv.KeyRequest\x1a\t.kv.Reply\x12\'\n\nReplicaPut\x12\x0e.kv.PutRequest\x1a\t.kv.Reply\x12*\n\rReplicaDelete\x12\x0e.kv.KeyRequest\x1a\t.kv.Reply\x12\x1c\n\x04Ping\x12\t.kv.Empty\x1a\t.kv.Reply\x12-\n\x07Recover\x12\x14.kv.PartitionRequest\x1a\x0c.kv.DataDumpb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kv_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DATADUMP_DATAENTRY']._loaded_options = None
  _globals['_DATADUMP_DATAENTRY']._serialized_options = b'8\001'
  _globals['_PUTREQUEST']._serialized_start=16
  _globals['_PUTREQUEST']._serialized_end=56
  _globals['_KEYREQUEST']._serialized_start=58
  _globals['_KEYREQUEST']._serialized_end=83
  _globals['_REPLY']._serialized_start=85
  _globals['_REPLY']._serialized_end=126
  _globals['_VALUEREPLY']._serialized_start=128
  _globals['_VALUEREPLY']._serialized_end=170
  _globals['_EMPTY']._serialized_start=172
  _globals['_EMPTY']._serialized_end=179
  _globals['_PARTITIONREQUEST']._serialized_start=181
  _globals['_PARTITIONREQUEST']._serialized_end=221
  _globals['_DATADUMP']._serialized_start=223
  _globals['_DATADUMP']._serialized_end=316
  _globals['_DATADUMP_DATAENTRY']._serialized_start=273
  _globals['_DATADUMP_DATAENTRY']._serialized_end=316
  _globals['_KVSERVICE']._serialized_start=319
  _globals['_KVSERVICE']._serialized_end=602
# @@protoc_insertion_point(module_scope)
